### ISSUE TITLE
gopages: Link to repository

### ISSUE THREAD

**Issue by lukasmalkmus** [JohnStarich/go#3]
Instead of including the whole code as static HTML, it would be nice to have a command line flag to configure the repositories base path:

When clicking the `Exit` func on https://johnstarich.com/go/gopages/pkg/github.com/johnstarich/go/gopages/cmd/ it would open https://github.com/JohnStarich/go/blob/master/gopages/cmd/exiter.go#L12 instead of https://johnstarich.com/go/gopages/src/github.com/johnstarich/go/gopages/cmd/exiter.go#L12.

An option could look like `-repo github.com/JohnStarich/go` which gets expanded to `https://<repo>/blob/master/<source-file-and-line>` where `<repo>` expands to the value given by flag and `<source-file-and-line>` to, well... The source file and line. In the above example, that would be `gopages/cmd/exiter.go#L12`.

GitHub and GitLab use the same syntax, so that should be covered.

**Comment by JohnStarich** [comment]
Sounds great to me 👍 

I've started a draft with my progress thus far #4
I figure a Go template for link generation is probably the most flexible approach.

**Comment by lukasmalkmus** [comment]
Awesome, looks great so far!

**Comment by JohnStarich** [comment]
@lukasmalkmus Released in version `v0.1.6` 🎉 

Let me know how it works out! 😄

**Comment by lukasmalkmus** [comment]
Works like a charm, thank you!
