### ISSUE TITLE
Use pkgsite instead of godoc to generate a Github pages site?

### ISSUE THREAD

**Issue by simonkotwicz** [JohnStarich/go#55]

**Comment by JohnStarich** [comment]
Hey @simonkotwicz, I'd love to. Last I checked though, pkgsite doesn't offer library-like functionality so I can't import and run it from my own program 😞 

I'd love to do this once pkgsite supports it though. I'll close for now, but we can keep the discussion going here. We could even re-open once pkgsite is usable.

**Comment by simonkotwicz** [comment]
I wonder if an approach similar to https://github.com/ktr0731/godoc-action/blob/18e9b17117cebd5ea657d8a3d9f0987acd1c08b3/main.bash#L13-L24 might work.
