### ISSUE TITLE
Generate docs with internal package

### ISSUE THREAD

**Issue by gdziwoki** [JohnStarich/go#6]
In some use cases (especially for internal projects) it might be beneficial to also generate docs for `internal` package.
It's currently being omited [here](https://github.com/JohnStarich/go/blob/master/gopages/internal/generate/generate.go#L64)
It would be nice to have a switch to enable it.

**Comment by JohnStarich** [comment]
@gdziwoki Definitely agree. Those internal docs are actually generated, but currently you need to know the package path to get there (see https://github.com/JohnStarich/go/commit/d61a1f302182de88f28e1f407a7f1b12183d5f23).

Feel free to open a PR to enable internal in the index pages! If I remember right, I had difficulty getting those to generate properly the first time.

**Comment by JohnStarich** [comment]
One of the problems I ran into was https://github.com/golang/go/issues/12092
Explicitly requesting internal docs didn’t always work for some reason.

**Comment by JohnStarich** [comment]
@gdziwoki Support added in `v0.1.18` via the new `--index-internal` flag. Let me know if you hit any issues!
