### ISSUE TITLE
remove usage of pipe package

### ISSUE THREAD

**Issue by 3052** [JohnStarich/go#61]
the pipe package:

https://johnstarich.com/go/pipe/pkg/github.com/johnstarich/go/pipe

adds a lot of overhead. because all values are inserted without a type:

~~~
func (p Pipe) Append(fn interface{}) Pipe
~~~

youre getting punished twice. first youre paying a performance cost to extract the value:

~~~
func (p Pipe) Do(args ...interface{}) ([]interface{}, error)
~~~

because you have to do a type assertion. then you also have the drawback of losing all type safety. instead of types being checked at compile time, they are now checked at runtime. and in most (all?) cases, a pipe is not needed. for example:

https://github.com/JohnStarich/go/blob/0cfead809946438d2fd835233ee2ad4e8c094281/gopages/main.go#L68-L81

can be written like this:

~~~go
func makeLinkerPipe(args flags.Args, modulePath string) (string, source.Linker, error) {
   modulePackage, err := module.Package(modulePath)
   if err != nil {
      return "", nil, err
   }
   linker, err := args.Linker(modulePackage)
   if err != nil {
      return "", nil, err
   }
   return modulePackage, linker, nil
}
~~~

the above code is actually LESS verbose than a pipe (11 lines versus 14), MORE performant since no type assertions, and MORE strongly typed, since checking happens as compile time.

**Comment by JohnStarich** [comment]
Those are all fair criticisms of pipe.

However, I disagree it should warrant removing this package from open source. I found it useful, so I wrote it and published it for others who may find it useful. Sometimes performance, verbosity, and compile-time type checks aren't the most important things.

**Comment by 3052** [comment]
> Sometimes performance, verbosity, and compile-time type checks aren't the most important things.

"Sometimes X isn't the most important thing" is fair, but when X is three items you've lost the argument, especially considering that you didn't provide a single justification of why your one thing outweighs the three. suit yourself.

**Comment by JohnStarich** [comment]
Each criticism you provided above is a tradeoff, not an absolute truth every program must have. If the tradeoffs it makes don't suit your programs, that's perfectly fine. You're welcome to use or not use the library, just like any other open source.

All of the justifications are clearly documented in the module's README.

> ... you've lost the argument, ...
>... cause writing Go like you are is just throwing away the whole point of strong typing.

You may be new to working in collaboration with the open source community, so a word of advice: Disrespectful comments like these don't help you and actively harm others.

On the other hand, respectful and thoughtful disagreements are welcome, appreciated, and may lead to an outcome you value. Might be worth a try.

As the [GitHub Community Guidelines](https://docs.github.com/en/site-policy/github-terms/github-community-guidelines) state:
>**Be respectful** - Working in a collaborative environment means disagreements may happen. But remember to criticize ideas, not people. Share thoughtful, constructive criticism and be courteous to those you interact with.
