### ISSUE TITLE
Prevent recursion into output folder?

### ISSUE THREAD

**Issue by ianrose14** [JohnStarich/go#62]
Hi!

I'm invoking like this:
> gopages -out godocs/

from within the main directory of my project (e.g. the same directory as go.mod, etc)

I find that `gopages` seems to be re-reading its own output as new input?  In other words, it is creating files like:
> godocs/index.html
> godocs/src/wattch/godocs/index.html
> godocs/src/wattch/godocs/src/wattch/godocs/index.html
> godocs/src/wattch/godocs/src/wattch/godocs/src/wattch/godocs/index.html
(etc)

After quite a long time, the program fails with this error:
> Error generating page [...] file name too long

Can I somehow tell `gopages` to exclude/ignore the output directory?

**Comment by pashagolub** [comment]
I can confirm this

**Comment by JohnStarich** [comment]
Huh, that’s odd! Do you have an example repo or module I could run this on to reproduce?

**Comment by pashagolub** [comment]
Sure! Try this one:

```terminal
git clone https://github.com/cybertec-postgresql/pgwatch.git

cd pgwatch

gopages -out "docs/godoc"
```

**Comment by JohnStarich** [comment]
Thanks!

So I've tried to reproduce with this repo, but I'm not hitting any errors or the recursive fun time going on for you. Granted I'm running on Linux, but I could try others to match your system.

Does this happen pretty consistently for you? Is there a specific file system (e.g. network share, Windows volume) or particular OS it occurs on?

**Comment by JohnStarich** [comment]
Oh and please share the Go version you used to install gopages and the version installed on the system gopages runs on.

I suspect the logic to run `go list $package_pattern` (via `golang.org/x/tools/go/packages`) is using the local Go version and is misbehaving.

**Comment by JohnStarich** [comment]
I've merged some dependency updates via #67 and cut release `gopages/v0.1.28`. Please let me know if that release fixed your issue!

**Comment by pashagolub** [comment]
Thanks, I'll try tomorrow!

**Comment by pashagolub** [comment]
No, the problem still persists for `gopages v0.1.28`

**Comment by JohnStarich** [comment]
Thank you for checking! If you have a moment, could you provide the info above so I could try to reproduce?

**Comment by pashagolub** [comment]
```
git clone https://github.com/cybertec-postgresql/pgwatch.git

cd pgwatch

gopages -out "docs/godoc"
```
This will never end and consume all space or throw OS error because of path limit. :) So it's wise to kill it ASAP. In "doc/godoc" you will find the recursion

**Comment by JohnStarich** [comment]
Can you provide more details about your machine and Go version?

I ran this on my machine and it completes successfully in about a second.

**Comment by pashagolub** [comment]
Sure!

```
go version go1.23.0 windows/amd64
Microsoft Windows 11 Pro 22621.1.amd64fre.ni_release.220506-1250
```

**Comment by pashagolub** [comment]
I tried to run test in docker container with Debian GNU/Linux 12 (bookworm) and can confirm there is no error on Linux.

**Comment by JohnStarich** [comment]
Got it, thanks! I can reproduce now. That's a mighty large directory O.O

**Comment by JohnStarich** [comment]
As a temporary work-around, you could run `gopages` without an output directory in your repo and move it into place afterward.

**Comment by pashagolub** [comment]
That's exactly what I do right now :)
