### ISSUE TITLE
Two-part key names

### ISSUE THREAD

**Issue by andrzejstopka** [JohnStarich/go#63]
Hi, is it possible to get two-part key names? 
I want to get <key>iTunes ID</key> or <key>app store link</key> but i don't know how

**Comment by JohnStarich** [comment]
Hey @andrzejstopka, are you asking about the plist package? Do you have an example demonstrating the problem you're hitting?

**Comment by andrzejstopka** [comment]
Thank you for response @JohnStarich, I have already managed with it :)
