### ISSUE TITLE
configure to ignore node_modules directory

### ISSUE THREAD

**Issue by dududko** [JohnStarich/go#7]
First of all I would like to thank you for implementing `gopages`, it did saved me a lot of time. I am surprised that after almost 10 years godoc still can not output the static data.

Would it be possible to configure the `gopages` to ignore certain folders like node_modules, dist, bazel-bin, etc. ? It would be even better if it could ignore directories and files based on `.gitignore` file. 
The issue I faced is that if I do not delete `node_modules` directory I get a panic:
```
Generating godoc static pages for module... github.com/dududko/xxx
panic: parse "/src/github.com/dududko/xxx/node_modules/aws-cdk/lib/init-templates/v1/app/csharp/src/%name.PascalCased%/": invalid URL escape "%na"
```

**Comment by JohnStarich** [comment]
@dududko Glad you found gopages useful! 😄 

Best I can tell, this should be fixed by #8 in `v0.1.7`. Can you confirm?

**Comment by JohnStarich** [comment]
A more ideal fix may be to ignore directories like `node_modules` somehow. However, I can imagine some cases where the gitignore shouldn't be used though, such as generated Go files with their own documentation.

I'd be open to discuss such an option if you're interested. I would need to know more about the use cases if we go down that path.

**Comment by dududko** [comment]
Thank you @JohnStarich, the panic is fixed now.
Hopefully in the next few weeks I will have time to work on this. Briefly about my usecase: multiple private repositories, a lot of generated code based on both internal and 3rd party openapi specs, bazel.
